### Numpy:

Numpy is the fundamental library for scientific computation in python. It provide support for arrays and matrices along with the collection of mathematical functions to operate on these data structures. In this lesson we will cover the basics of Numpy, focusing on arrays and vectorixed operations.

In [2]:
import numpy as np

In [3]:
## Creating Arrays using numpy

#Creat a 1D Array
arr1= np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [ ]:
## Reshaping array into two dimensional array
arr2= np.array([1,2,3,4,5])
arr2.reshape(1,5) #It will reshape array into 1 row and 5 column...


array([[1, 2, 3, 4, 5]])

In [11]:
#We can create it directlt 

arr2= np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [16]:
# adding multiple rows

arr2= np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2)
print(arr2.shape) #Now it will display 2 rows and 5 columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [19]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
#Creating an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Attributes of numpy Array
arr= np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("size(Number of elemnets):", arr.size)
print("Data type:", arr.dtype)
print("Items size(in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Number of dimensions: 2
size(Number of elemnets): 6
Data type: int64
Items size(in bytes): 8


In [7]:
#Numpy Vectorized operations
arr1= np.array([1,2,3,4,5])
arr2= np.array([10,20,30,45,50])

# Element wise addition
print("addition:", arr1+arr2)

# Element wise subtraction
print("Subtraction:", arr2-arr1)

#Element wise multiplication
print("Multiplication:", arr1*arr2)

#Element wise division
print("Division", arr2/arr1)

addition: [11 22 33 49 55]
Subtraction: [ 9 18 27 41 45]
Multiplication: [ 10  40  90 180 250]
Division [10.   10.   10.   11.25 10.  ]


In [11]:
#Universal Function:

arr= np.array([1,2,3,4,5])

#Square root
print(np.sqrt(arr))

#Exponential 

print(np.exp(arr))

#Sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
#Array slicing and Indexing

arr= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("array: \n", arr)

array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [18]:
print(arr[0][0])
print(arr[1][0])
print(arr[2][0])

1
6
11


In [ ]:
print(arr[0:2,3:]) # ineeded the last 2 columns of first 2 rows

[[ 4  5]
 [ 9 10]]


In [31]:
print(arr[0:2, 1:3]) ## I needed the 2nd and 3rd column of first 2 rows

[[2 3]
 [7 8]]


In [33]:
#Modify erray elements:
arr[0,0]=100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [37]:
arr[2][4]= 78
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  78]]


In [40]:
arr[1:]=100
print(arr)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [42]:
arr[0:2]=0
print(arr)

[[  0   0   0   0   0]
 [  0   0   0   0   0]
 [100 100 100 100 100]]


In [50]:
## Statistical concept --- Normalization
#To have a mean of 0 and standard deviation of 1

#Noramalization is a process to convert data in succh a way that mean become 0 and std deviation becomes 1

data= np.array([1,2,3,4,5])

#calculating the mean and standard deviation
mean= np.mean(data)
std_dev= np.std(data)

print("Mean before Normaliztion is:", mean)
print("Standard Deviation beofre normaliztion is:", std_dev)

#Normalizing the data

normalized_data= (data- mean)/std_dev
print(normalized_data)



Mean before Normaliztion is: 3.0
Standard Deviation beofre normaliztion is: 1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [57]:
data= np.array([1,2,3,4,5,6,7,8,9,10])

mean= np.mean(data)
print(mean)

median=np.median(data)
print(median)

std_dev= np.std(data)
print(std_dev)

varaince= np.var(data)
print(varaince)

5.5
5.5
2.8722813232690143
8.25


In [61]:
#Logical Operation
data= np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>3) & (data<7)]

array([4, 5, 6])